### ISSUE TITLE
sample-apps - CLI v2 Invalid base64 error on lambda invoke

### ISSUE THREAD

**Issue by Raptormstr** [awsdocs/aws-lambda-developer-guide#180]
The AWS CLI v2 has a breaking change in which it treats a **file://** CLI option as base64-encoded text. 
https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam

This breaks the 4-invoke.sh script lambda invoke call.
https://github.com/awsdocs/aws-lambda-developer-guide/blob/ed29db606a6a8a42c6fef5ffaa01db59cd4837c0/sample-apps/blank-java/4-invoke.sh#L6

One fix is to add the argument **--cli-binary-format raw-in-base64-out** which reverts the call back to CLI v1 behavior.

**Comment by mwunderl** [comment]
Hi Stephen,

Thanks for your feedback. Unfortunately, adding that argument is messy and breaks the command for the v1 CLI. I wonder if there's a way to avoid using `file://` completely. If you're not otherwise using `file://` with base64-encoded data, I'd suggest setting the option in `~/.aws/config` as mentioned in the topic you linked:

```
cli_binary_format=raw-in-base64-out
```

Thanks,
-Michael

**Comment by neelakansha85** [comment]
I ran into this same issue today. I understand the need to keep it backward compatible, would it atleast help by adding a note in the Readme doc somewhere?

I am aware that the requirements section clearly mention to use AWS CLI v1 but I would imagine most people might be already having aws cli v2 installed and may not even notice this issue until after experiencing it.

**Comment by mwunderl** [comment]
I think we can make this work by changing `--payload file://event.json` to `--payload "$(cat events/kinesis.json)"`. I've tested this with the v1 CLI on WSL Ubuntu Bash. Please check with your setup and let me know if it works.

Thanks,
-Michael

**Comment by neelakansha85** [comment]
Thanks for looking into this Michael.
I tried changing `--payload file://event.json` to `--payload "$(cat events/kinesis.json)"` but it doesn't necessarily work because we do not have kinesis.json file and simply ignores the payload at that time. This is equivalent to not passing `--payload` option as it doesn't log custom Event Records  from our events.json file. It does invoke the Lambda function and log other events from the function and can be misleading. 

Using `--payload "$(cat events.json)"` fails with the original issue error on v2 CLI since it requires payload to be base64 encoded by default.

I did notice that using `--payload fileb://events.json` works fine for both v1 and v2 CLI though I am not sure if this is a feature or a bug with the logic in `fileb://` as I would have expected it to throw some kind of error saying the file is not a binary file.

**Comment by mwunderl** [comment]
Sorry that was a typo, I meant to say `"$(cat event.json)"`. Sounds like it won't work though. Another option is to add `cli_binary_format=raw-in-base64-out` to `~/.aws/config` if you use v2 of the CLI. Then it should work with the hundreds (thousands?) of existing examples that use `file://` to load parameters from a JSON file.

**Comment by memark** [comment]
Is there a fix coming? Still getting the invalid base64 error for Python. This repo is linked to from the official AWS documentation, would be nice if it worked.

**Comment by jpascoe** [comment]
I fixed by converting to base64

PAYLOAD=$(cat ./events/xxxxxxxx.json | base64)
aws lambda invoke --function-name $FUNCTION --payload $PAYLOAD out.json

**Comment by zhangbin0027** [comment]
The cli-binary-format option is required if you are using AWS CLI version.

**Comment by mwunderl** [comment]
Updated the invoke scripts to use `fileb://` instead of `file://` in https://github.com/awsdocs/aws-lambda-developer-guide/pull/450
Tested with 3 sample apps so far on WSL2 with CLI versions 1 and 2.
