### ISSUE TITLE
VSCode: "Error with child process: Error: libs is an Invalid Layer Arn." when trying to debug sample-apps/blank-python

### ISSUE THREAD

**Issue by orodri** [awsdocs/aws-lambda-developer-guide#203]
I ran the `2-build-layer.sh` script and added a debug configuration using the "Add Debug Configuration" Code Lens that appeared above the function declared in `sample-apps/blank-python/template.yml`. Ultimately I am trying to debug a python lambda with a layer dependency locally on VSCode using the AWSToolkit.

**Comment by mwunderl** [comment]
The `Layers` field in the template refers to the layer resource by name. The [Ref function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html) here resolves to an ARN after the layer resource is created in the CloudFormation stack. I took a look at the template with the toolkit debug config in VSCode and don't see an error. Looks like this has since been fixed in the toolkit.
