### ISSUE TITLE
Does lambda-insights support nodejs 14?

### ISSUE THREAD

**Issue by Yehonal** [awsdocs/aws-lambda-developer-guide#264]
If you look at the guide here: https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/monitoring-insights.md#supported-runtimes

The nodejs 14 runtime is not listed, but it's currently supported by lambda. So my question is, does the lambda-insights version 12 currently supports the nodejs 14?

If so, shall we update that documentation?

**Comment by devlinbd2** [comment]
Thank you for pointing out the issue. Since Lambda insights is an extension, it is supported on the runtimes that support extensions (which includes Node.js 14). I will update the source file, but it may take a week before the GitHub version gets updated. The list of runtimes that support extensions is here:
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html
