### ISSUE TITLE
Clarifications and corrections needed

### ISSUE THREAD

**Issue by zackriso** [awsdocs/aws-lambda-developer-guide#403]
1. Under the "Security" Section, it mentions that "Security groups control inbound and outbound traffic for your instances, and network ACLs control inbound and outbound traffic for your subnets". 

I believe it would be better to use the word Lambda instead of instances for this context. 

2. It should be mentioned and clarified in the docs page under "VPC networking for Lambda" that when a Lambda is configured as part of a VPC, it would still be possible to trigger it, through Lambda-URLs for example, completely from the Internet. This is true without the presence of any Internet Gateways attached to the VPC, nor any inbound Security groups attached to the Lambda's VPC configuration. While triggers are part of the Control Plane APIs, if we did the exact same thing on a EC2 (ex. an API to start the EC2), this would not necessarily mean that we would be able to serve an HTTP page from a web server in that EC2 (even if that Web server was already configured).  Lambda therefore inhibits a particular behavior which should be clarified and explained. 

Thank you, please let me know if you I need to clarify things a bit more.

**Comment by mwunderl** [comment]
Thanks for your feedback. 
https://docs.aws.amazon.com/lambda/latest/dg/foundation-networking.html

> I believe it would be better to use the word Lambda instead of instances for this context.

Connecting a Lambda function to a VPC lets you connect to network resources that run in the VPC. The security group controls access to those resources. It doesn't control access to the Lambda service. We can say "resources" instead of instances to include for example EFS access points.

> It should be mentioned and clarified in the docs page under "VPC networking for Lambda" that when a Lambda is configured as part of a VPC, it would still be possible to trigger it, through Lambda-URLs for example, completely from the Internet

Functions don't have a public URL by default. Adding one is similar to adding a public IP address to an EC2 instance, or connecting an API gateway. The function is still hosted in the Lambda service, and your VPC is not involved. I'll look for a place to clarify this in the topic.

**Comment by mwunderl** [comment]
Updated "instances" in source.
